#!/bin/bash
cd Sona;
echo "Executing pod install";
pod install;
echo "Downloading Nuance Speechkit Framework";
cd Sona;
curl -L https://www.dropbox.com/s/er8k6k6h44lkuhi/SpeechKit.framework.zip?dl=1 -o SpeechKit.framework.zip;
echo "Extracting Nuance Speechkit Framework";
unzip SpeechKit.framework.zip;
echo "Removing zip";
rm SpeechKit.framework.zip;
echo "Done!";
