#!/usr/bin/env node

var path     = require('path');
var fs       = require('fs.extra');
var color    = require('colors');
var request  = require('request');
var utils    = require('./utils.js');
var pack     = require('./package.json');
var uploader = require('file-uploader');

var args = process.argv.slice(2);
var demo = true;
var config = utils.getConfig();

if (!args.length)
  return;

try {
  var filename = utils.lodir('commands/', args[0]);
  var cmd = require(filename);
  cmd.run(args);
} catch(e) {
  console.log('Could not find ' + args[0].red);
  return;
}